- this repo is created for labs from csdt cource
- details about task:
I'm making a demo project for a graduate work.
Leading professor is Galyna Klym.
Task is to make a digital synth.

Task 1. Initiate GIT repository (BEF)
Task 2. Create simple game (BEF)
Task 3. Create tests (BEF)
Task 4 (20 extra points). Create pipelines
Task 5. Create new version (FEF)
Task 6. Implement AI (FEF)
Task 7. Implement DB (FEF)

- student number - 12, student name - Nazar Koval
